version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: CORE
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: express_server
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./server:/app
      - /app/node_modules
      - /app/dist
      
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: nextjs_client
    ports:
      - "8080:8080"
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next

volumes:
  postgres_data: