import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@mui/material";
import { AlertProvider } from "@/shared/context/AlertContext";
import { UserProvider } from "@/shared/context/UserContext";
import theme from "@/shared/theme/AppTheme";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
                <ThemeProvider theme={theme}>
                    {/* <StyledEngineProvider injectFirst> */}
                    <AlertProvider>
                        <UserProvider>
                            {children}
                        </UserProvider>
                    </AlertProvider>
                    {/* </StyledEngineProvider> */}
                </ThemeProvider>
            </body>
        </html>
    );
}
